// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAB3nmKLSs9yVJiwyvXlpkA8Lezqc8YEY',
    appId: '1:88005311371:android:27e81e69bcf6cecbde0d8e',
    messagingSenderId: '88005311371',
    projectId: 'park-wheels-e2bdd',
    databaseURL: 'https://park-wheels-e2bdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'park-wheels-e2bdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXxFDageLnn2inLwObjqFl_tf3mFKV6KI',
    appId: '1:88005311371:ios:79b3f1d347a9dac2de0d8e',
    messagingSenderId: '88005311371',
    projectId: 'park-wheels-e2bdd',
    databaseURL: 'https://park-wheels-e2bdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'park-wheels-e2bdd.appspot.com',
    iosClientId: '88005311371-jblepuibi62j77a0cdv9od1kefriaakk.apps.googleusercontent.com',
    iosBundleId: 'in.parkwheels.parkWheels',
  );
}
